name:                termslang
version:             0.1.0.0
github:              "termslang/terms-haskell"
license:             GPLv2
author:              "Michael Baynov"
maintainer:          "m.baynov@gmail.com"
copyright:           "2018 Michael Baynov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/termslang/terms-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- text
- text-conversions
- cryptonite >= 0.24 && < 1

library:
  source-dirs: src

executables:
  termslang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - termslang

tests:
  termslang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - termslang
